# charts/frontend/environments/prod-values.yaml
replicaCount: 3

ingress:
  hosts:
    - host: frontend.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: frontend-tls
      hosts:
        - frontend.example.com

env:
  API_URL: http://backend-api.backend-prod.svc.cluster.local
  DEBUG: "false"
