# charts/backend-api/values.yaml
replicaCount: 1

image:
  repository: nginx  # Placeholder image, replace with your actual backend image
  tag: 1.21
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

postgresql:
  enabled: true
  auth:
    username: backend
    database: backend
  primary:
    persistence:
      size: 1Gi